#!/usr/bin/env bash
# Update and install Nginx.
agt-get -y update
apt-get -y install nginx

# Install HAproxy v1.8
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get -y install haproxy=1.8.\*

# Enable HAproxy to start at boot
sed -i '8iENABLED=1' /etc/default/haproxy

# Configure load balancer backend with HAproxy.
proxy_config='/etc/haproxy/haproxy.cfg'
echo -e "backend web-backend" >> $proxy_config
echo -e "\tmode http" >> $proxy_config
echo -e "\tbalance roundrobin" >> $proxy_config
echo -e "\tserver 229-web-01 52.200.24.63 listen port 80" >> $proxy_config
echo -e "\tserver 229-web-02 54.144.25.175 list port 80" >> $proxy_config

# Configure load balancer frontend with HAproxy.
echo -e "frontend http" >> $proxy_config
echo -e "\tbind *:80" >> $proxy_config
echo -e "\tmode http" >> $proxy_config
echo -e "\tdefault_backend web-backend" >> $proxy_config

# Restart
service haproxy restart
