#!/usr/bin/env bash
# Reconfigures the sites-enabled server block to listen on port 80.
wget https://github.com/jagrvargen/holberton-system_engineering-devops/blob/master/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
service nginx reload
service nginx restart
