#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely on a 2 second sleep delay,
# followed by "I am invincible!!!" if SIGTERM signal is received.
while true
 do
  echo "To infinity and beyond"
  trap "echo I am vincible!!!" SIGTERM
  sleep 2
done
