#!/usr/bin/env bash
# Parses an Apache log access file and returns the visitor IP addresses as well
# as their corresponding HTTP status codes.
awk 'match($1,/([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)/) { print $1 " " $9}' apache-access.log
