#!/usr/bin/env bash
# Loop from 1 to 10, display 'bad luck' on 4th iteration, 'good luck' on
# 8th iteration, and 'Holberton School' all others.
i=1
while [ $i -le 10 ]
 do
  if [ $i -eq 4 ]
   echo "bad luck"
  elif [ $i -eq 8 ]
   echo "good luck"
  else
   echo "Holberton School"
  (( i += 1 ))
done
