#!/usr/bin/env bash
# A loop from 1 to 10 that displays 'bad luck' on its 4th iteration,
# 'good luck' on its 8th iteration, and 'Holberton School' on all others.
i=1
while [ $i -le 10 ]
 do
  if [ $i -eq 4 ]
   then echo "bad luck"
  elif [ $i -eq 8 ]
   then echo "good luck"
  else
   echo "Holberton School"
  fi
  (( i += 1 ))
done
