#!/usr/bin/env bash
# Displays the content of the current directory in a list format where only
# the part of the name after the first dash is displayed.
LIST="$(ls)"
for item in $LIST
 do echo "$item" | cut -d '-' -f 2
done
