#!/usr/bin/env bash
# Checks if the file holbertonschool exists, if it is empty, and if it is
# regular.
FILE="holbertonschool"
if [ -e $FILE ]
 then echo "$FILE file exists"
else
 echo "$FILE file does not exist"
fi
if [ -s $FILE ]
 then echo "$FILE file is not empty"
elif [ -e $FILE ]
 then echo "$FILE is empty"
fi
if [ -f $FILE ]
 then echo "$FILE is a regular file"
fi
