#!/usr/bin/env bash
# 301 redirects /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
redirect="location /redirect_me {\n\t\trewrite ^/.*$ https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sed -i "27i$redirect" /etc/nginx/sites-available/default
service nginx restart
